# Generated by Django 5.0.6 on 2024-06-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('gen', models.CharField(max_length=150, unique=True, verbose_name='Порода')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка')], max_length=6, null=True, verbose_name='Пол')),
                ('color', models.CharField(max_length=150, unique=True, verbose_name='Цвет')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
