# Generated by Django 5.0.6 on 2024-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='color',
            field=models.CharField(max_length=150, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='req',
            name='desc',
            field=models.TextField(verbose_name='Дополнительная атрибутика'),
        ),
        migrations.AlterField(
            model_name='req',
            name='gen',
            field=models.CharField(max_length=150, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='req',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
