# Generated by Django 5.0.6 on 2024-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_req_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='status',
            field=models.CharField(choices=[('approved', 'Одобрена'), ('rejected', 'Не одобрена')], default='approved', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
