# Generated by Django 5.0.6 on 2024-06-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('gen', models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка')], max_length=6, null=True, verbose_name='Пол')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=7, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Попугай',
                'verbose_name_plural': 'Попугаи',
                'db_table': 'popug',
            },
        ),
    ]
